### ISSUE TITLE
Add stable version 1.0.0

### ISSUE THREAD

**Issue by Shotman** [Smile-SA/magento2-module-elasticsuite-quick-order#1]
Hello, 
Could you create a tag to have a stable version available on packagist ? Right now only the dev-master version is available.

Thanks

**Comment by tr33m4n** [comment]
I 2nd this, as this module is required for Elasticsuite to work correctly with B2B, please release a stable tag @romainruaud

**Comment by romainruaud** [comment]
Thank you for pinging me on this one, it was out of my radar actually.

Tag is released,

Sorry for the delay and thank you !

**Comment by tr33m4n** [comment]
@romainruaud Thanks for the swift response 👍

**Comment by tr33m4n** [comment]
@romainruaud The tagged version has still not appeared in packagist
