### ISSUE TITLE
Compatibility with Magento >= 2.3.5 & Elasticsuite >2.9.0

### ISSUE THREAD

**Issue by ghost** [Smile-SA/magento2-module-elasticsuite-quick-order#2]
The requirements in `composer.json` still specify `elasticsuite` with a constraint of `^2.5.8`. Is this module still required to integrate Quickorder with Elasticsuite and if so is an update planned?

**Comment by rbayet** [comment]
Hello @rob-aimes,

This is a bit of a late answer, but yes, this module is still necessary as it stands for Elasticsuite 2.9.x and Elasticsuite 2.10.x.

I've just published a bunch of new releases to mirror our Elasticsuite versions pattern : 2.6.0, 2.8.0, 2.9.0 and 2.10.1.
There is no actual code difference between releases 2.6.0, 2.8.0, 2.9.0 and the historic 1.0.0 release of this module.

On the other hand, if you moved to Magento >= 2.4.1 & Elasticsuite 2.10.2, you will need the 2.10.1 release which fixes an actual issue in Magento 2.4.1.

Regards,
