### ISSUE TITLE
Magento 2.4.6 compatibility

### ISSUE THREAD

**Issue by Sharkozp** [Smile-SA/magento2-module-elasticsuite-quick-order#7]
Hello,

Magento 2.4.6 has been released. For this reason **smile/elasticsuite** has been updated to version 2.11.0. Your **composer.json** is using ~2.10.0.

Are there any plans to update this module?

**Comment by zhulak** [comment]
Hi,

this is something that we are interrested in knowing as well!
Would be good to know if you plan on doing this and if so, what would be the expected time frame to get this done?

If there is no plan to update this to support 2.4.6, please let us know as soon as possible so we can move forward with our project in another way.

Thanks in advance either way!

**Comment by rqsakai** [comment]
PR to fix this https://github.com/Smile-SA/magento2-module-elasticsuite-quick-order/pull/8

**Comment by romainruaud** [comment]
2.11.0 tag was created.

Thank you all
